#!/usr/bin/env bash
# Deploy both Mistral Document AI models (v25.12 + OCR 4.0) and auto-generate .env.
#
# Usage:
#   ./scripts/deploy_all.sh --account-name "my-ai-foundry" --resource-group "rg-demo"
#
# Requires: az CLI logged in with sufficient permissions.
# Note: mistral-ocr-4-0 is Preview and requires a GlobalStandard deployment.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"

ACCOUNT_NAME=""
RESOURCE_GROUP=""
CAPACITY=1

usage() {
    echo "Usage: $0 --account-name <name> --resource-group <rg> [--capacity <n>]"
    exit 1
}

while [[ $# -gt 0 ]]; do
    case "$1" in
        --account-name)   ACCOUNT_NAME="$2"; shift 2 ;;
        --resource-group) RESOURCE_GROUP="$2"; shift 2 ;;
        --capacity)       CAPACITY="$2"; shift 2 ;;
        *) usage ;;
    esac
done

[[ -z "$ACCOUNT_NAME" || -z "$RESOURCE_GROUP" ]] && usage

echo "=== Mistral Document AI - Deploy All Models ==="

# 1. Verify az CLI session
echo -e "\n[1/4] Verifying Azure CLI session..."
if ! az account show &>/dev/null; then
    echo "Not logged in. Running 'az login'..."
    az login
fi
SUB=$(az account show --query "name" -o tsv)
echo "  Subscription: $SUB"

# 2. Verify Microsoft Foundry account
echo -e "\n[2/4] Checking Microsoft Foundry account '${ACCOUNT_NAME}'..."
ENDPOINT=$(az cognitiveservices account show \
    --name "$ACCOUNT_NAME" \
    --resource-group "$RESOURCE_GROUP" \
    --query "properties.endpoint" -o tsv 2>/dev/null)

if [[ -z "$ENDPOINT" ]]; then
    echo "ERROR: Microsoft Foundry account '$ACCOUNT_NAME' not found." >&2
    exit 1
fi
echo "  Endpoint: $ENDPOINT"

# 3. Deploy models
echo -e "\n[3/4] Deploying models..."

deploy_model() {
    local deploy_name="$1"
    local model_name="$2"
    local model_version="$3"
    local model_format="${4:-Mistral AI}"

    echo -e "\n  --- $deploy_name ---"
    EXISTING=$(az cognitiveservices account deployment show \
        --name "$ACCOUNT_NAME" \
        --resource-group "$RESOURCE_GROUP" \
        --deployment-name "$deploy_name" \
        --query "properties.model.name" -o tsv 2>/dev/null || true)

    if [[ -n "$EXISTING" ]]; then
        echo "    Already exists: $EXISTING"
    else
        echo "    Creating deployment..."
        az cognitiveservices account deployment create \
            --name "$ACCOUNT_NAME" \
            --resource-group "$RESOURCE_GROUP" \
            --deployment-name "$deploy_name" \
            --model-name "$model_name" \
            --model-version "$model_version" \
            --model-format "$model_format" \
            --sku-name "GlobalStandard" \
            --sku-capacity "$CAPACITY"
        echo "    Created!"
    fi
}

deploy_model "mistral-document-ai-2512" "mistral-document-ai-2512" "1" "Mistral AI"
deploy_model "mistral-ocr-4-0" "mistral-ocr-4-0" "1" "Mistral AI"

# 4. Get API key and write .env
echo -e "\n[4/4] Writing .env file..."
KEY=$(az cognitiveservices account keys list \
    --name "$ACCOUNT_NAME" \
    --resource-group "$RESOURCE_GROUP" \
    --query "key1" -o tsv 2>/dev/null || true)

ENV_FILE="$PROJECT_DIR/.env"
cat > "$ENV_FILE" <<EOF
# Auto-generated by deploy_all.sh on $(date '+%Y-%m-%d %H:%M:%S')
# Microsoft Foundry endpoint
MISTRAL_ENDPOINT=$ENDPOINT

# Model deployments
MISTRAL_DEPLOYMENT_OCR4=mistral-ocr-4-0
MISTRAL_DEPLOYMENT_2512=mistral-document-ai-2512

# API version
MISTRAL_API_VERSION=2024-05-01-preview

# Authentication (API Key)
AZURE_AI_KEY=$KEY
EOF
echo "  Written: $ENV_FILE"

echo -e "\n=== All models deployed and .env configured ==="
echo "Next: uv sync && uv run streamlit run app.py"
