<#
.SYNOPSIS
    Deploy both Mistral Document AI models (v25.05 + v25.12) and auto-generate .env.
.DESCRIPTION
    Deploys mistral-document-ai-2505 and mistral-document-ai-2512 on an existing
    Microsoft Foundry account, retrieves the endpoint and API key, and writes
    the .env file automatically.
    Requires: az CLI logged in with sufficient permissions.
.PARAMETER AccountName
    Name of the Azure AI Services / Foundry account.
.PARAMETER ResourceGroup
    Resource group containing the account.
.PARAMETER Capacity
    Token-per-minute capacity units per model (default: 1).
.EXAMPLE
    .\scripts\deploy_all.ps1 -AccountName "my-ai-foundry" -ResourceGroup "rg-demo"
#>
param(
    [Parameter(Mandatory)][string]$AccountName,
    [Parameter(Mandatory)][string]$ResourceGroup,
    [int]$Capacity = 1
)

$ErrorActionPreference = "Stop"

# Model definitions
$Models = @(
    @{
        DeploymentName = "mistral-document-ai-2505"
        ModelName      = "mistral-document-ai-2505"
        ModelVersion   = "25.05"
    },
    @{
        DeploymentName = "mistral-document-ai-2512"
        ModelName      = "mistral-document-ai-2512"
        ModelVersion   = "25.12"
    }
)

Write-Host "=== Mistral Document AI - Deploy All Models ===" -ForegroundColor Cyan

# 1. Check az CLI login
Write-Host "`n[1/4] Verifying Azure CLI session..."
$account = az account show --output json 2>$null | ConvertFrom-Json
if (-not $account) {
    Write-Host "Not logged in. Running 'az login'..." -ForegroundColor Yellow
    az login
    $account = az account show --output json | ConvertFrom-Json
}
Write-Host "  Subscription: $($account.name) ($($account.id))"

# 2. Verify Microsoft Foundry account exists
Write-Host "`n[2/4] Checking Microsoft Foundry account '$AccountName'..."
$aiAccount = az cognitiveservices account show `
    --name $AccountName `
    --resource-group $ResourceGroup `
    --output json 2>$null | ConvertFrom-Json

if (-not $aiAccount) {
    Write-Error "Microsoft Foundry account '$AccountName' not found in resource group '$ResourceGroup'."
    exit 1
}
$endpoint = $aiAccount.properties.endpoint
Write-Host "  Endpoint: $endpoint"

# 3. Deploy each model
Write-Host "`n[3/4] Deploying models..."
foreach ($model in $Models) {
    $dName = $model.DeploymentName
    Write-Host "`n  --- $dName ---"

    $existing = az cognitiveservices account deployment show `
        --name $AccountName `
        --resource-group $ResourceGroup `
        --deployment-name $dName `
        --output json 2>$null | ConvertFrom-Json

    if ($existing) {
        Write-Host "    Already exists: $($existing.properties.model.name) v$($existing.properties.model.version)" -ForegroundColor Green
    } else {
        Write-Host "    Creating deployment..."
        az cognitiveservices account deployment create `
            --name $AccountName `
            --resource-group $ResourceGroup `
            --deployment-name $dName `
            --model-name $model.ModelName `
            --model-version $model.ModelVersion `
            --model-format "Mistral" `
            --sku-name "GlobalStandard" `
            --sku-capacity $Capacity `
            --output json | Out-Null

        Write-Host "    Created!" -ForegroundColor Green
    }
}

# 4. Get API key and write .env
Write-Host "`n[4/4] Writing .env file..."
$keys = az cognitiveservices account keys list `
    --name $AccountName `
    --resource-group $ResourceGroup `
    --output json 2>$null | ConvertFrom-Json

$envPath = Join-Path $PSScriptRoot ".." ".env"
$envContent = @"
# Auto-generated by deploy_all.ps1 on $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")
# Microsoft Foundry endpoint
MISTRAL_ENDPOINT=$endpoint

# Model deployments
MISTRAL_DEPLOYMENT=mistral-document-ai-2505
MISTRAL_DEPLOYMENT_2512=mistral-document-ai-2512

# API version
MISTRAL_API_VERSION=2024-05-01-preview

# Authentication (API Key)
AZURE_AI_KEY=$($keys.key1)
"@
Set-Content -Path $envPath -Value $envContent -Encoding UTF8
Write-Host "  Written: $envPath" -ForegroundColor Green

Write-Host "`n=== All models deployed and .env configured ===" -ForegroundColor Cyan
Write-Host "Next: uv sync && uv run streamlit run app.py"
