#!/usr/bin/env bash
# Resolve Microsoft Foundry configuration and generate the .env file.
#
# Queries an existing Microsoft Foundry account to discover the endpoint,
# deployed Mistral Document AI models, and retrieves an API key.
# Writes the .env file with all values required by the app.
#
# This does NOT deploy models — use deploy_all.sh for that.
# Requires: az CLI logged in with sufficient permissions.
#
# Usage:
#   ./scripts/setup_env.sh --account-name "my-ai-foundry" --resource-group "rg-demo"
#   ./scripts/setup_env.sh --account-name "my-ai-foundry" --resource-group "rg-demo" --auth aad
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"

ACCOUNT_NAME=""
RESOURCE_GROUP=""
AUTH_MODE="key"

usage() {
    echo "Usage: $0 --account-name <name> --resource-group <rg> [--auth key|aad]"
    exit 1
}

while [[ $# -gt 0 ]]; do
    case "$1" in
        --account-name)   ACCOUNT_NAME="$2"; shift 2 ;;
        --resource-group) RESOURCE_GROUP="$2"; shift 2 ;;
        --auth)           AUTH_MODE="$2"; shift 2 ;;
        *) usage ;;
    esac
done

[[ -z "$ACCOUNT_NAME" || -z "$RESOURCE_GROUP" ]] && usage

echo "=== Mistral Document AI - .env Setup ==="

# 1. Verify az CLI session
echo -e "\n[1/4] Verifying Azure CLI session..."
if ! az account show &>/dev/null; then
    echo "Not logged in. Running 'az login'..."
    az login
fi
SUB=$(az account show --query "name" -o tsv)
echo "  Subscription: $SUB"

# 2. Resolve endpoint from Microsoft Foundry account
echo -e "\n[2/4] Resolving Microsoft Foundry account '${ACCOUNT_NAME}'..."
ENDPOINT=$(az cognitiveservices account show \
    --name "$ACCOUNT_NAME" \
    --resource-group "$RESOURCE_GROUP" \
    --query "properties.endpoint" -o tsv 2>/dev/null)

if [[ -z "$ENDPOINT" ]]; then
    echo "ERROR: Microsoft Foundry account '$ACCOUNT_NAME' not found in resource group '$RESOURCE_GROUP'." >&2
    exit 1
fi
echo "  Endpoint: $ENDPOINT"

# 3. Discover deployed Mistral Document AI models
echo -e "\n[3/4] Discovering Mistral Document AI deployments..."
DEPLOYMENTS_JSON=$(az cognitiveservices account deployment list \
    --name "$ACCOUNT_NAME" \
    --resource-group "$RESOURCE_GROUP" \
    --output json 2>/dev/null)

DEPLOYMENT_OCR4=""
DEPLOYMENT_2512=""

if command -v jq &>/dev/null; then
    DEPLOYMENT_OCR4=$(echo "$DEPLOYMENTS_JSON" | jq -r '[.[] | select((.name | test("ocr-?4"; "i"))) | .name] | first // empty')
    DEPLOYMENT_2512=$(echo "$DEPLOYMENTS_JSON" | jq -r '[.[] | select(.name | contains("2512")) | .name] | first // empty')
else
    # Fallback: parse with grep
    DEPLOYMENT_OCR4=$(echo "$DEPLOYMENTS_JSON" | grep -oiP '"name"\s*:\s*"[^"]*ocr-?4[^"]*"' | head -1 | grep -oiP '(?<=")[^"]*ocr-?4[^"]*(?=")' || true)
    DEPLOYMENT_2512=$(echo "$DEPLOYMENTS_JSON" | grep -oP '"name"\s*:\s*"[^"]*2512[^"]*"' | head -1 | grep -oP '(?<=")[^"]*2512[^"]*(?=")' || true)
fi

if [[ -n "$DEPLOYMENT_OCR4" ]]; then
    echo "  Found OCR 4.0: $DEPLOYMENT_OCR4"
else
    echo "  WARNING: No OCR 4.0 deployment found. Using default name 'mistral-ocr-4-0'."
    echo "  Run ./scripts/deploy_all.sh to deploy it."
    DEPLOYMENT_OCR4="mistral-ocr-4-0"
fi

if [[ -n "$DEPLOYMENT_2512" ]]; then
    echo "  Found v25.12: $DEPLOYMENT_2512"
else
    echo "  WARNING: No v25.12 deployment found. Using default name 'mistral-document-ai-2512'."
    echo "  Run ./scripts/deploy_all.sh to deploy it."
    DEPLOYMENT_2512="mistral-document-ai-2512"
fi

# 4. Retrieve API key (if key auth mode)
echo -e "\n[4/4] Configuring authentication (mode: $AUTH_MODE)..."
API_KEY=""
if [[ "$AUTH_MODE" == "key" ]]; then
    API_KEY=$(az cognitiveservices account keys list \
        --name "$ACCOUNT_NAME" \
        --resource-group "$RESOURCE_GROUP" \
        --query "key1" -o tsv 2>/dev/null || true)
    if [[ -n "$API_KEY" ]]; then
        echo "  API key retrieved."
    else
        echo "  WARNING: Could not retrieve API key. You can set AZURE_AI_KEY manually."
    fi
else
    echo "  Azure AD mode: AZURE_AI_KEY left empty. Use 'az login' to authenticate."
fi

# Write .env
ENV_FILE="$PROJECT_DIR/.env"
cat > "$ENV_FILE" <<EOF
# Auto-generated by setup_env.sh on $(date '+%Y-%m-%d %H:%M:%S')
# Microsoft Foundry endpoint (your Foundry project endpoint)
MISTRAL_ENDPOINT=$ENDPOINT

# Deployment names (discovered from Microsoft Foundry)
MISTRAL_DEPLOYMENT_OCR4=$DEPLOYMENT_OCR4
MISTRAL_DEPLOYMENT_2512=$DEPLOYMENT_2512

# API version for Mistral Document AI
MISTRAL_API_VERSION=2024-05-01-preview

# Authentication
# Option A: API Key (for dev/testing)
AZURE_AI_KEY=$API_KEY
# Option B: Azure AD / Managed Identity (recommended for production)
# Leave AZURE_AI_KEY empty and authenticate via 'az login'
EOF
echo -e "\n.env written: $ENV_FILE"

# Summary
echo -e "\n=== .env Summary ==="
echo "  MISTRAL_ENDPOINT       = $ENDPOINT"
echo "  MISTRAL_DEPLOYMENT_OCR4= $DEPLOYMENT_OCR4"
echo "  MISTRAL_DEPLOYMENT_2512= $DEPLOYMENT_2512"
echo "  MISTRAL_API_VERSION    = 2024-05-01-preview"
if [[ -n "$API_KEY" ]]; then
    echo "  AZURE_AI_KEY           = ****${API_KEY: -4}"
else
    echo "  AZURE_AI_KEY           = (empty - Azure AD mode)"
fi
echo -e "\nNext: uv sync && uv run streamlit run app.py"
