<#
.SYNOPSIS
    Resolve Microsoft Foundry configuration and generate the .env file.
.DESCRIPTION
    Queries an existing Microsoft Foundry account to discover the endpoint,
    deployed Mistral Document AI models, and retrieves an API key.
    Writes the .env file with all values required by the app.

    This does NOT deploy models — use deploy_all.ps1 for that.
    Requires: az CLI logged in with sufficient permissions.
.PARAMETER AccountName
    Name of the Azure AI Services / Foundry account.
.PARAMETER ResourceGroup
    Resource group containing the account.
.PARAMETER AuthMode
    Authentication mode: "key" (writes API key to .env) or "aad" (leaves key empty for Azure AD).
    Default: "key".
.EXAMPLE
    .\scripts\setup_env.ps1 -AccountName "my-ai-foundry" -ResourceGroup "rg-demo"
.EXAMPLE
    .\scripts\setup_env.ps1 -AccountName "my-ai-foundry" -ResourceGroup "rg-demo" -AuthMode "aad"
#>
param(
    [Parameter(Mandatory)][string]$AccountName,
    [Parameter(Mandatory)][string]$ResourceGroup,
    [ValidateSet("key", "aad")][string]$AuthMode = "key"
)

$ErrorActionPreference = "Stop"

Write-Host "=== Mistral Document AI - .env Setup ===" -ForegroundColor Cyan

# 1. Verify az CLI session
Write-Host "`n[1/4] Verifying Azure CLI session..."
$account = az account show --output json 2>$null | ConvertFrom-Json
if (-not $account) {
    Write-Host "Not logged in. Running 'az login'..." -ForegroundColor Yellow
    az login
    $account = az account show --output json | ConvertFrom-Json
}
Write-Host "  Subscription: $($account.name) ($($account.id))"

# 2. Resolve endpoint from Microsoft Foundry account
Write-Host "`n[2/4] Resolving Microsoft Foundry account '$AccountName'..."
$aiAccount = az cognitiveservices account show `
    --name $AccountName `
    --resource-group $ResourceGroup `
    --output json 2>$null | ConvertFrom-Json

if (-not $aiAccount) {
    Write-Error "Microsoft Foundry account '$AccountName' not found in resource group '$ResourceGroup'."
    exit 1
}
$endpoint = $aiAccount.properties.endpoint
Write-Host "  Endpoint: $endpoint" -ForegroundColor Green

# 3. Discover deployed Mistral Document AI models
Write-Host "`n[3/4] Discovering Mistral Document AI deployments..."
$deployments = az cognitiveservices account deployment list `
    --name $AccountName `
    --resource-group $ResourceGroup `
    --output json 2>$null | ConvertFrom-Json

$deployment2505 = ""
$deployment2512 = ""

foreach ($dep in $deployments) {
    $modelName = $dep.properties.model.name
    $depName = $dep.name
    if ($modelName -like "*2505*" -or $depName -like "*2505*") {
        $deployment2505 = $depName
        Write-Host "  Found v25.05: $depName ($modelName v$($dep.properties.model.version))" -ForegroundColor Green
    }
    if ($modelName -like "*2512*" -or $depName -like "*2512*") {
        $deployment2512 = $depName
        Write-Host "  Found v25.12: $depName ($modelName v$($dep.properties.model.version))" -ForegroundColor Green
    }
}

if (-not $deployment2505) {
    Write-Host "  WARNING: No v25.05 deployment found. Using default name 'mistral-document-ai-2505'." -ForegroundColor Yellow
    Write-Host "  Run .\scripts\deploy_all.ps1 to deploy it." -ForegroundColor Yellow
    $deployment2505 = "mistral-document-ai-2505"
}
if (-not $deployment2512) {
    Write-Host "  WARNING: No v25.12 deployment found. Using default name 'mistral-document-ai-2512'." -ForegroundColor Yellow
    Write-Host "  Run .\scripts\deploy_all.ps1 to deploy it." -ForegroundColor Yellow
    $deployment2512 = "mistral-document-ai-2512"
}

# 4. Retrieve API key (if key auth mode)
Write-Host "`n[4/4] Configuring authentication (mode: $AuthMode)..."
$apiKey = ""
if ($AuthMode -eq "key") {
    $keys = az cognitiveservices account keys list `
        --name $AccountName `
        --resource-group $ResourceGroup `
        --output json 2>$null | ConvertFrom-Json
    if ($keys) {
        $apiKey = $keys.key1
        Write-Host "  API key retrieved." -ForegroundColor Green
    } else {
        Write-Host "  WARNING: Could not retrieve API key. You can set AZURE_AI_KEY manually." -ForegroundColor Yellow
    }
} else {
    Write-Host "  Azure AD mode: AZURE_AI_KEY left empty. Use 'az login' to authenticate." -ForegroundColor Green
}

# Write .env
$envPath = Join-Path $PSScriptRoot ".." ".env"

$envContent = @"
# Auto-generated by setup_env.ps1 on $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")
# Microsoft Foundry endpoint (your Foundry project endpoint)
MISTRAL_ENDPOINT=$endpoint

# Deployment names (discovered from Microsoft Foundry)
MISTRAL_DEPLOYMENT=$deployment2505
MISTRAL_DEPLOYMENT_2512=$deployment2512

# API version for Mistral Document AI
MISTRAL_API_VERSION=2024-05-01-preview

# Authentication
# Option A: API Key (for dev/testing)
AZURE_AI_KEY=$apiKey
# Option B: Azure AD / Managed Identity (recommended for production)
# Leave AZURE_AI_KEY empty and authenticate via 'az login'
"@

Set-Content -Path $envPath -Value $envContent -Encoding UTF8
Write-Host "`n.env written: $envPath" -ForegroundColor Green

# Summary
Write-Host "`n=== .env Summary ===" -ForegroundColor Cyan
Write-Host "  MISTRAL_ENDPOINT       = $endpoint"
Write-Host "  MISTRAL_DEPLOYMENT     = $deployment2505"
Write-Host "  MISTRAL_DEPLOYMENT_2512= $deployment2512"
Write-Host "  MISTRAL_API_VERSION    = 2024-05-01-preview"
if ($apiKey) {
    Write-Host "  AZURE_AI_KEY           = ****$(($apiKey)[-4..-1] -join '')"
} else {
    Write-Host "  AZURE_AI_KEY           = (empty - Azure AD mode)"
}
Write-Host "`nNext: uv sync && uv run streamlit run app.py" -ForegroundColor Cyan
